### ISSUE TITLE
Swift 4 web proxy in swift

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk-runtime-swift#5]
Today we use python web server to execute the swift binary.
python will pass input JSON via stdin and expect executable to respond with the last line of stdout as the output JSON.

The problems is that the swift code needs to initialize everything on every invoke. if creates instances of a Class, or reads a file into an instance. this work needs to be done from scratch on every invoke.

Other runtimes like nodejs and python in OpenWhisk don't have this problem, since the web proxy server is in the same language and holds into memory.

It would be good to have a web proxy server to be implemented in swift, this way anything created on /init or /run can remain in memory as long the container lives.

One alternative is look into Kitura 2.0 to build a very small and fast web proxy that listens on port 8080 that handles the standard OW interface with /init and /run

**Comment by csantanapr** [comment]
We might use in the interim a go proxy which seems to be faster than the python flask that we use today.

**Comment by dgrove-oss** [comment]
Closing, as we are using the go proxy now
