### ISSUE TITLE
Swift 3.1.1 image fails to build due to timeout

### ISSUE THREAD

**Issue by houshengbo** [apache/openwhisk-runtime-swift#82]
Step 11/13 : RUN python /swift3Action/buildandrecord.py && rm /swift3Action/spm-build/.build/release/Action

The build failed at this line, when the swift 3.1.1 image was being built. It always timed out, since there is no response.

**Comment by dgrove-oss** [comment]
proposing to remove Swift 3.1.1 runtime in #114
