### ISSUE TITLE
Feature Request: Pg/MySQL/SQLite

### ISSUE THREAD

**Issue by krugazor** [apache/openwhisk-runtime-swift#94]
#### In other runtimes

- PHP supports PDO (and many of its flavors)
- Many other runtimes can just include it

#### But Swift doesn't handle pg/mysql/...

Natively? No. However, [libraries](https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL.git) [can](https://github.com/IBM-Swift/SwiftKueryMySQL) [be used](https://github.com/IBM-Swift/Swift-Kuery-SQLite).

Low level languages can be much more performant, and it would allow to share code with iOS/Android apps.

#### Actually...

Maybe they should be included in almost all of the runtimes. Accessing a DB is part and parcel of micro-services work, and actions would benefit from that as well, to avoid passing huge JSON files across a sequence.

#### I know... Docker

But it requires a different set of skills, plus pushing a container to DockerHub, etc... That's a lot of friction.

**Comment by dgrove-oss** [comment]
Closing as stale
